/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const insight_Logic = require('./code/insight-logic');
const myApplicationLogic = require('./code/MyApplicationLogic');

class loyaltyProgramSrv extends LCAPApplicationService {
    async init() {

        this.on('READ', 'Insight', async (request, next) => {
            await insight_Logic(request);
            return next();
        });
        const em_sap_s4_beh_PaymentReceipt = await cds.connect.to('sap.s4.beh.PaymentReceipt');
        em_sap_s4_beh_PaymentReceipt.on('Created.v1', async message => {
            await myApplicationLogic(message);
        });

        return super.init();
    }
}


module.exports = {
    loyaltyProgramSrv
};